apiVersion: v1
kind: Service
metadata:
  name: grafana2
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: grafana2
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
