---
- hosts: all
  become: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install haproxy
      apt: 
        name: haproxy 
        state: present

    - name: copy HaProxy config
      command: cp -r ./haproxy.cfg  /etc/haproxy/haproxy.cfg

    - name: Restart haproxy
      service:
        name: haproxy
        daemon_reload: yes
        state: restarted
