---
- hosts: all
  become: true
  tasks:
  - name: Configure resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      insertbefore: BOF
      line: nameserver 185.51.200.2

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p $HOME/.kube
     - cp -i /vagrant/admin.conf $HOME/.kube/config
     - chown $(id -u):$(id -g) $HOME/.kube/config
     
  - name: install kubectl
    shell: snap install kubectl --classic

  - name: Setup calico network
    shell: curl https://docs.projectcalico.org/manifests/calico.yaml -O

  - name: apply calico
    command: kubectl apply -f calico.yaml

  # - name: setup galera cluster
  #   command: "{{ item }}"
  #   with_items:
  #    - kubectl create -f galera/etcd-cluster.yaml
  #    - kubectl create -f galera/mariadb-pv.yaml
  #    - kubectl create -f galera/mariadb-pvc.yaml
  #    - kubectl create -f galera/mariadb-ss.yaml

  - name: setup helm
    shell: "{{ item }}"
    with_items:
     - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
     - chmod +x get_helm.sh
     - ./get_helm.sh
     - helm repo add stable https://charts.helm.sh/stabl

  # - name: setup rook ceph
  #   command: "{{ item }}"
  #   with_items:
  #    - kubectl create -f rook-ceph/crds.yaml -f rook-ceph/common.yaml -f rook-ceph/operator.yaml
  #    - kubectl create -f rook-ceph/cluster.yaml
  #    - kubectl create -f rook-ceph/toolbox.yaml
  
  # - name: setup prometheus
  #   command: "{{ item }}"
  #   with_items:
  #    - kubectl create namespace monitoring
  #    - kubectl create -f prometheus/clusterRole.yaml
  #    - kubectl create -f prometheus/config-map.yaml
  #    - kubectl create -f prometheus/prometheus-deployment.yaml 
  #    - kubectl create -f prometheus/prometheus-service.yaml --namespace=monitoring

  # - name: setup prometheus alert manager and grafana
  #   command: "{{ item }}"
  #   with_items:
  #    - git clone https://github.com/prometheus-operator/kube-prometheus.git
  #    - kubectl create -f kube-prometheus/manifests/setup
  #    - kubectl create -f kube-prometheus/manifests/

  - name: nginx-ingress controller
    command: "{{ item }}"
    with_items:
     - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
     - kubectl apply -f ingress/nginx-ingress.yaml

