apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: dev
  labels:
    app: hello
spec:
  type: ClusterIP
  selector:
    app: hello
  type: NodePort
  ports:
  - port: 80
    targetPort: 7575
    nodePort: 32075
    protocol: TCP
