---
- hosts: all
  vars:
    jenkins_jre: openjdk-8-jre
    jenkins_jdk: openjdk-8-jdk

  become: true
  tasks:
  # - name: Install JRE and JDK
  #   apt: 
  #     name: "{{ item }}"
  #     update_cache: yes
  #     #install_recommends: no
  #   items:
  #   - "{{ jenkins_jre }}"
  #   - "{{ jenkins_jdk }}"
  - name: Add APT key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
  - name: ensure the repository is configured
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  # - name: Copy jenkins.list to /etc/apt/sources.list.d/jenkins.list
  #   copy:
  #     src: ./jenkins.list
  #     dest: /etc/apt/sources.list.d/jenkins.list
  - name: Install Jenkins
    apt: 
      name: jenkins
      state: present
      update_cache: yes
  - name: ensure jenkins is running
    service: name=jenkins state=started
